CREATE TABLE [QLESS].[CardType]
(
	[Id] SMALLINT NOT NULL PRIMARY KEY, 
    [Name] VARCHAR(30) NOT NULL, 
    [Rate] DECIMAL(5, 2) NOT NULL DEFAULT 0, 
    [InitialLoad] DECIMAL(7, 2) NOT NULL DEFAULT 0
)
